AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for EventPublisher

Resources:
  EventPublisherFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: EventPublisherFunction
      Handler: iansteph.nhlp3.eventpublisher.handler.EventPublisherHandler::handleRequest
      Runtime: java8
      Role:
        Fn::GetAtt:
          - EventPublisherExecutionRole
          - Arn

  EventPublisherExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Description: IAM Role assumed when invoking the Event Publisher lambda function
      RoleName: NHLP3-Event-Publisher-Execution-Role-Prod
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        -
          PolicyName: EventPublishingPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Effect: Allow
                Action:
                  - sns:Publish
                Resource:
                  Ref: NHLP3EventsSnsTopic
              -
                Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Resource: 'arn:aws:dynamodb:us-east-1:627812672245:table/NhlPlayByPlayProcessingAggregate'

  NHLP3EventsSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: NHLP3-Play-by-Play-Events-Prod

  NHLP3EventsSnsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - Ref: NHLP3EventsSnsTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Sid: AllowAllAwsAccountSubscriptions
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - sns:Subscribe
            Resource:
              Ref: NHLP3EventsSnsTopic
          -
            Sid: OnlyEventPublisherExecutionRoleCanPublishMessagesToSnsTopic
            Effect: Allow
            Principal:
              AWS:
                Fn::GetAtt:
                  - EventPublisherExecutionRole
                  - Arn
            Action:
              - sns:Publish
            Resource:
              Ref: NHLP3EventsSnsTopic